name: Main Branch Pipeline
on:
  push:
    branches:
      - 'main'
run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
jobs:
  call-workflow-passing-data:
    uses: raghudevopsb81/github-reusable-actions/.github/workflows/ci-main.yaml@main